spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/biccw
    username: postgres
    password: E30sMGxbP5WzNkhHIo0h 

kie:
  url: http://localhost:8080/kie-server/services/rest/server
  user: kieserver
  password: kieserver1!
  message: kie working!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
processtimer:
  message: timer's on and on!
