server:
  port: 10301

spring:
  application:
    name: bicexec-service-scheduler
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.7.0.227:5432/biccw
    username: postgres
    password: E30sMGxbP5WzNkhHIo0h 

logging:
  level: 
    com: INFO
    com.arvato.biccw: INFO  


kie:
  url: http://37.139.121.74:8080/kie-server/services/rest/server
  user: kieserver
  password: kieserver1!
  

      
     
